from enum import Enum

class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class TaskStatus(str, Enum):
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    COMPLETED = "COMPLETED"

class LoadStatus(str, Enum):
    SAFE = "SAFE"
    WARNING = "WARNING"
    OVERLOAD = "OVERLOAD"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"

class Tier(str, Enum):
    FREE = "FREE"
    PRO = "PRO"
    TEAM = "TEAM"

LOAD_SAFE_THRESHOLD = 60.0
LOAD_WARNING_THRESHOLD = 85.0
RISK_LOW_THRESHOLD = 30
RISK_MEDIUM_THRESHOLD = 70
SCORE_WEIGHT_SKILL = 40
SCORE_WEIGHT_WORKLOAD = 25
SCORE_WEIGHT_AVAILABILITY = 20
SCORE_WEIGHT_PRIORITY = 15
PRIORITY_HIGH_MULTIPLIER = 1.1
SKILL_LEVEL_MIN = 1
SKILL_LEVEL_MAX = 5
JOIN_CODE_LENGTH = 6
